# Generated by Django 5.1.2 on 2024-10-30 19:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0002_bankaccount_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('budget_type', models.CharField(choices=[('account', 'Account Based'), ('category', 'Category Based')], max_length=10)),
                ('category', models.CharField(blank=True, choices=[('bills', 'Bills & Utilities'), ('food', 'Food & Dining'), ('shopping', 'Shopping'), ('transport', 'Transportation'), ('entertainment', 'Entertainment'), ('health', 'Healthcare'), ('credit', 'Credit Card Payment'), ('income', 'Income'), ('transfer', 'Transfer'), ('other', 'Other')], help_text='Required for category-based budgets', max_length=20, null=True)),
                ('allocation_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Balance')], max_length=10)),
                ('allocation_amount', models.DecimalField(decimal_places=2, help_text='Fixed amount or percentage depending on allocation type', max_digits=10)),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly')], default='monthly', max_length=10)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('current_amount_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, help_text='Required for account-based budgets', null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'account', 'period_type'), ('user', 'category', 'period_type')},
            },
        ),
    ]
