# Generated by Django 5.1.1 on 2024-11-02 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_bankaccount_user'),
        ('budget', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('account__isnull', False)), fields=('user', 'account', 'period_type'), name='unique_account_budget'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('user', 'category', 'period_type'), name='unique_category_budget'),
        ),
    ]
