# Generated by Django 5.1.1 on 2024-11-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_budget_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='allocation_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='allocation_type',
            field=models.CharField(default='fixed', max_length=10),
        ),
    ]
