# Generated by Django 5.1.2 on 2024-10-22 00:13

import bank.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('savings', 'Savings Account'), ('checking', 'Checking Account'), ('credit', 'Credit Card')], max_length=10)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('account_no', models.CharField(default=bank.models.BankAccount.generate_account_number, max_length=6, unique=True)),
                ('routing_no', models.CharField(default=bank.models.BankAccount.generate_routing_number, max_length=10, unique=True)),
                ('finance_institution', models.CharField(choices=[('JPM', 'JPMorgan Chase'), ('BOA', 'Bank of America'), ('WF', 'Wells Fargo'), ('CITI', 'Citi Bank'), ('PNC', 'PNC Bank'), ('US', 'U.S. Bank'), ('GSB', 'Goldman Sachs Bank'), ('TRU', 'Truist Bank'), ('CAP1', 'Capital One'), ('TD', 'TD Bank')], default='NOT DISCLOSED', max_length=20)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('name_on_card', models.CharField(blank=True, max_length=100, null=True)),
                ('card_institution', models.CharField(blank=True, choices=[('AMEX', 'American Express'), ('DISC', 'Discover'), ('MASTER', 'Mastercard'), ('VISA', 'Visa')], max_length=20, null=True)),
            ],
        ),
    ]
