# Generated by Django 5.1.2 on 2024-10-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('savings', 'Savings Account'), ('checking', 'Checking Account')], max_length=10)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
