# Generated by Django 5.1.2 on 2024-10-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='account_holder',
            new_name='account_name',
        ),
    ]
