# Generated by Django 5.1.2 on 2024-10-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='card_institution',
            field=models.CharField(blank=True, choices=[('AMEX', 'American Express'), ('DISC', 'Discover'), ('MASTER', 'Mastercard'), ('VISA', 'Visa')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='name_on_card',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
