# Generated by Django 5.1.2 on 2024-10-22 05:39

import django.db.models.deletion
import django.utils.timezone
import transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default=transactions.models.Transaction.generate_transaction_id, editable=False, max_length=10, unique=True)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('withdraw', 'Withdraw'), ('deposit', 'Deposit')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bankaccount', to_field='account_no')),
            ],
        ),
    ]
