# Generated by Django 5.1.1 on 2024-10-23 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
