# Generated by Django 5.1.2 on 2024-10-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_remove_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('bills', 'Bills & Utilities'), ('food', 'Food & Dining'), ('shopping', 'Shopping'), ('transport', 'Transportation'), ('entertainment', 'Entertainment'), ('health', 'Healthcare'), ('credit', 'Credit Card Payment'), ('income', 'Income'), ('transfer', 'Transfer'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
