# Generated by Django 5.1.1 on 2024-11-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10),
        ),
    ]
