# Generated by Django 5.1.1 on 2024-11-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurring', '0002_alter_recurringtransaction_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='category',
            field=models.CharField(choices=[('bills', 'Bills & Utilities'), ('food', 'Food & Dining'), ('shopping', 'Shopping'), ('transport', 'Transportation'), ('entertainment', 'Entertainment'), ('health', 'Healthcare'), ('credit', 'Credit Card Payment'), ('income', 'Income'), ('transfer', 'Transfer'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
