# Generated by Django 5.1.1 on 2024-11-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurring', '0003_recurringtransaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='frequency',
            field=models.CharField(choices=[('one_minute', 'Every 1 Minute'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10),
        ),
    ]
