# Generated by Django 5.1.1 on 2024-11-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurring', '0004_alter_recurringtransaction_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='frequency',
            field=models.CharField(choices=[('one_minute', 'Every 1 Minute'), ('monthly', 'Monthly')], max_length=10),
        ),
    ]
